#!/bin/bash


echo "Content-type: text/html"
echo ""
cd /home/pi/Pi-in-the-Sky/
git fetch
BRANCHES=`git branch`
TOBRANCH=$QUERY_STRING

BRANCHEXISTS=`echo $BRANCHES | grep $TOBRANCH`

if [ "$BRANCHEXISTS" != "" ]
then
	echo "$TOBRANCH" > /var/local/switchBranch.txt 
	echo "Success!! Your branch will be switched to within 5 minutes"
else
	echo "Not a valid branch"
fi
