#!/bin/bash


echo "Content-type: text/html"
echo ""
cd /home/pi/Pi-in-the-Sky/
git fetch
BRANCHES=`git branch`
TOBRANCH=$QUERY_STRING

BRANCHEXISTS=`echo $BRANCHES | grep $TOBRANCH`

if [ "$BRANCHEXISTS" != "" ]
then
	git checkout $TOBRANCH
	echo "Success!!"
else
	echo "Not a valid branch"
fi
